# -*- coding: utf-8 -*-
"""Time_Series_using_R.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZsF4NRRv1cKy67qqdhka54m3ij2v-kQ
"""

#R language
library(fpp2)
library(ggplot2)

# Function to create and print a time plot
create_time_plot <- function(data, title, y_label = NULL) {
  plot <- autoplot(data) +
    ggtitle(title) +
    xlab("Time")

  if (!is.null(y_label)) {
    plot <- plot + ylab(y_label)
  }

  print(plot)
}

# bicoal
data(bicoal)
create_time_plot(bicoal, "Bituminous Coal Production", "Millions of Short Tons")

#chicken
data(chicken)
create_time_plot(chicken, "Price of Chicken", "Cents per Pound")

#dole
data(dole)
create_time_plot(dole, "Unemployment Benefits", "Number of Benefits")

#usdeaths
data(USAccDeaths)
create_time_plot(USAccDeaths, "US Accidental Deaths", "Number of Deaths")

# lynx
data(lynx)
create_time_plot(lynx, "Annual Canadian Lynx Trappings", "Number of Lynx Trapped")

# goog
data(goog)
autoplot(goog) +
  ggtitle("Google Stock Price") +
  xlab("Date") +
  ylab("Closing Price (USD)")

#  writing
data(writing)
create_time_plot(writing, "Writing Test Scores", "Score")

# fancy
data(fancy)
create_time_plot(fancy, "Fancy Cheese Consumption", "Pounds per Capita")

#a10
data(a10)
create_time_plot(a10, "Monthly Anti-Diabetic Drug Sales in Australia", "Sales ($ million)")

#h02
data(h02)
create_time_plot(h02, "Monthly Retail Sales of Building Materials", "Sales ($ million)")

install.packages('fpp2')
library('fpp2')

library(fpp2)

# Function to create all plots for a given time series
create_plots <- function(data, title) {
  p1 <- autoplot(data) + ggtitle(paste(title, "- Time Plot"))
  p2 <- ggseasonplot(data) + ggtitle(paste(title, "- Seasonal Plot"))
  p3 <- ggsubseriesplot(data) + ggtitle(paste(title, "- Subseries Plot"))
  p4 <- gglagplot(data) + ggtitle(paste(title, "- Lag Plot"))
  p5 <- ggAcf(data) + ggtitle(paste(title, "- ACF Plot"))

  print(p1)
  print(p2)
  print(p3)
  print(p4)
  print(p5)
}

#plots for each time series
create_plots(hsales, "Housing Sales")
create_plots(USAccDeaths, "US Accidental Deaths")
create_plots(bricksq, "Clay Brick Production")
create_plots(sunspotarea, "Sunspot Area")
create_plots(gasoline, "Gasoline Demand")

library(fpp2)
library(ggplot2)


data(arrivals)

#Time plot
autoplot(arrivals) +
  ggtitle("International Arrivals to Australia") +
  ylab("Arrivals (thousands)") +
  theme(legend.position = "bottom")

#Function to create seasonal plot for a single country
create_seasonal_plot <- function(data, country) {
  ggseasonplot(data[, country], year.labels = TRUE, year.labels.left = TRUE) +
    ggtitle(paste("Seasonal Plot:", country, "Arrivals to Australia")) +
    ylab("Arrivals (thousands)")
}

#Function to create subseries plot for a single country
create_subseries_plot <- function(data, country) {
  ggsubseriesplot(data[, country]) +
    ggtitle(paste("Subseries Plot:", country, "Arrivals to Australia")) +
    ylab("Arrivals (thousands)")
}

#plots for each country
countries <- c("Japan", "NZ", "UK", "US")
for (country in countries) {
  print(create_seasonal_plot(arrivals, country))
  print(create_subseries_plot(arrivals, country))
}

After carefully analyzing the time plots and ACF plots provided, I determined the following matches:

Daily temperature of cow (Time plot 1) corresponds to ACF plot A.
Reasoning: The time plot shows rapid, irregular fluctuations without clear seasonality or trend. This results in an ACF plot that quickly drops off after lag 0 with some small, irregular spikes, which is exactly what we see in plot A.
Monthly accidental deaths (Time plot 2) matches with ACF plot B.
Reasoning: The time plot displays clear seasonal patterns repeating annually. This produces an ACF plot with regular spikes at lags corresponding to the seasonal period (likely 12 months for monthly data), which is evident in plot B.
Monthly air passengers (Time plot 3) aligns with ACF plot C.
Reasoning: The time plot shows a strong upward trend and possibly increasing seasonal variation. This leads to an ACF plot with very high values that decrease slowly, indicating strong positive autocorrelation at many lags, as seen in plot C.
Annual mink trappings (Time plot 4) corresponds to ACF plot D.
Reasoning: The time plot exhibits cyclical behavior but no clear trend or consistent seasonality. This results in an ACF plot with values that decrease very slowly, showing long-term correlations, which is precisely what plot D demonstrates.

Hence the matching will be:
figure 1 is to figure A
figure 2 is to figure B
figure 3 is to figure C
figure 4 is to figure D